### ISSUE TITLE
Update for future changes

### ISSUE THREAD

**Issue by Plailect** [rourke/age-chrome#1]
The guide is going to be massively updated very soon to be completely restructured and shortened. 

Please execute `git clone -b ctrtransfer https://github.com/Plailect/Guide.wiki.git` to view the branch of the wiki containing the soon-to-be added changes, and prepare an update for this extension to match.

**Comment by gingerbeardman** [comment]
@Plailect what does this mean?

`If you already have an EmuNAND CFW setup, this guide deals exclusively with SysNAND and you should follow all instructions from within or applying to SysNAND.`

...from within or applying to?

**Comment by Plailect** [comment]
Do all steps from inside sysnand.

If a step does not explicitly say EmuNAND, assume sysnand.

**Comment by gingerbeardman** [comment]
OK. I feel it could be clearer, sorry
